In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import random
import sklearn

In [3]:
final_df = pd.read_csv('data/final_plot_release_cleaned.csv')
final_df

,Unnamed: 0,Name,Countries,Genres,Budget(USD)_Inflated,Domestic(USD)_Inflated,Domestic_Percentage,Foreign(USD)_Inflated,Foreign_Percentage,Worldwide(USD)_Inflated,Runtime(mins),Rating,Audience_Score,Critics_Score,plot_summary,Month,Day,Year
0,0,10 cloverfield lane,united states of america,"drama, horror, sci-fi, thriller",6.076746e+06,8.760602e+07,0.654010,4.634613e+07,0.345990,1.339521e+08,103,pg-13,0.79,0.91,"After surviving a car accident, Michelle (Mary...",Mar,11,2016
1,2,"10,000 bc",united states of america,"thriller, adventure, costume drama, action/adv...",1.441563e+08,1.301309e+08,0.351333,2.402606e+08,0.648667,3.703914e+08,109,pg-13,0.37,0.10,Mammoth hunter D'Leh (Steven Strait) has long ...,Mar,7,2008
2,4,12 rounds,united states of america,"action thrillers, thriller, action, crime fiction",2.726275e+07,1.667757e+07,0.708013,6.877890e+06,0.291987,2.355546e+07,108,pg-13,0.45,0.31,When New Orleans cop Danny Fisher (John Cena) ...,Mar,27,2009
3,5,12 strong,united states of america,"action, drama, history, war",3.979050e+07,5.209113e+07,0.644274,2.876133e+07,0.355726,8.085246e+07,130,r,0.62,0.50,"In the wake of Sept. 11, Capt. Mitch Nelson le...",Jan,19,2018
4,6,12 years a slave,united states of america,"biography, drama, history",2.539260e+07,7.195247e+07,0.301875,1.663993e+08,0.698125,2.383517e+08,134,r,0.90,0.95,"In the years before the Civil War, Solomon Nor...",Oct,18,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2705,3861,zoolander,united states of america,"parody, comedy of errors, comedy",4.851315e+07,7.826600e+07,0.743197,2.704388e+07,0.256803,1.053099e+08,90,pg-13,0.80,0.64,Propelled to the top of the fashion world by a...,Sep,28,2001
2706,3862,zoolander 2,united states of america,"action, adventure, comedy, mystery, romance",6.076746e+07,3.506124e+07,0.508592,3.387664e+07,0.491408,6.893788e+07,101,pg-13,0.20,0.22,Former models Derek Zoolander (Ben Stiller) an...,Feb,12,2016
2707,3863,zoom,united states of america,"science fiction, action, fantasy, adventure",5.014200e+07,1.717625e+07,0.958658,7.407176e+05,0.041342,1.791697e+07,93,pg,0.34,0.05,"Capt. Zoom, or Jack (Tim Allen), as he is now ...",Aug,11,2006
2708,3864,zootopia,united states of america,"action, adventure, animation, comedy, crime, f...",1.823024e+08,4.147601e+08,0.333340,8.294952e+08,0.666660,1.244255e+09,108,pg,0.92,0.98,From the largest elephant to the smallest shre...,Mar,4,2016
2709,3865,aeon flux,united states of america,"thriller, science fiction, action, adventure, ...",9.055065e+07,3.778932e+07,0.485250,4.008668e+07,0.514750,7.787601e+07,93,pg-13,0.39,0.10,"In the 25th century, the Earth's population ha...",Dec,2,2005

## Defining classification target

In [ ]:
import pandas as pd

# Assuming final_df is your DataFrame
final_df["Domestic_Higher"] = (final_df["Domestic_Percentage"] > final_df["Foreign_Percentage"]).astype(int)